### ISSUE TITLE
I want to add space on Bottom, Offset is not working 

### ISSUE THREAD

**Issue by huzaifasaeed** [cleveradssolutions/CAS-Flutter#1]
I am using this code to set padding from bottom
bannerView?.showBanner();
bannerView?.setBannerPositionWithOffset(AdPosition.BottomCenter, 0, 50);

**Comment by Jedures** [comment]
Hello, thank you for notification of your issue. We are working on changing the logic of banners and you can use them as widgets in the next update

**Comment by huzaifasaeed** [comment]
Sure, Eagerly awaiting for the update.

**Comment by huzaifasaeed** [comment]
@Jedures  Any updates regrading this?

**Comment by huzaifasaeed** [comment]
> Hello, thank you for notification of your issue. We are working on changing the logic of banners and you can use them as widgets in the next update

@Jedures Still not able to use them as widget.
