### ISSUE TITLE
MREC and Native Ads support missing

### ISSUE THREAD

**Issue by huzaifasaeed** [cleveradssolutions/CAS-Flutter#2]
Please Add MREC and Native Ads support in CAS-Flutter

**Comment by Jedures** [comment]
Hello, thank you for notification of your issue. Our CAS SDK doesn't support native ads for now but we support MREC banners. You can find more information here https://github.com/cleveradssolutions/CAS-Flutter/wiki/Banner-Ads#ad-size 

MREC (MediumRectangle) is a 300x250 banner

**Comment by huzaifasaeed** [comment]
@Jedures How can i use them as widget in Container?
