### ISSUE TITLE
minSdkVersion is 21 while CAS seems to use Platform Views which require api 23.

### ISSUE THREAD

**Issue by wszak** [cleveradssolutions/CAS-Flutter#25]
This exception seems to come from your code:
PlatformException(error, Platform views cannot be displayed below API level 23 You can prevent this issue by setting `minSdkVersion: 23` in build.gradle.

Can you check it? 
If it's confirmed, maybe you could still make it so that API 21 is enough?

**Comment by kraativ** [comment]
Thank you for creating the issue. The minimum API level for Android is set to 23. Unfortunately, we cannot support lower API levels.
