### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by wszak** [cleveradssolutions/CAS-Flutter#26]
Got this error via Sentry:

MissingPluginException(No implementation found for method dispose on channel com.cleveradssolutions.plugin.flutter/banner.[#95eda]) #0      MethodChannel._invokeMethod 

Ver: 0.6.3 + 3.9.7

**Comment by kraativ** [comment]
Thank you for creating the issue. The problem is fixed in version 0.7.0.
