### ISSUE TITLE
IOS Help

### ISSUE THREAD

**Issue by malikaraa** [cleveradssolutions/CAS-Flutter#7]
[!] Unable to find a specification for `CleverAdsSolutions-Base (~> 3.5.4)` depended upon by `clever_ads_solutions`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Jedures** [comment]
Hello, can you check did you added our sources to your Podfile?
https://github.com/cleveradssolutions/CAS-Flutter/wiki/Include-iOS#2-add-podfile-header

**Comment by malikaraa** [comment]
> Merhaba, kaynaklarımızı Podfile'inize eklediniz mi kontrol edebilir misiniz? https://github.com/cleveradssolutions/CAS-Flutter/wiki/Include-iOS#2-add-podfile-header

Do I need to add it to projectName/ios/Podfile?

**Comment by malikaraa** [comment]
> Merhaba, kaynaklarımızı Podfile'inize eklediniz mi kontrol edebilir misiniz? https://github.com/cleveradssolutions/CAS-Flutter/wiki/Include-iOS#2-add-podfile-header

[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/macbookpro/projeler/dogdating2/ios/Pods/CleverAdsSolutions-Base/libs/CleverAdsSolutions.xcframework)
 I'm getting the error now too

**Comment by Jedures** [comment]
Did you add this use_frameworks! :linkage => :static to your Podfile?

**Comment by malikaraa** [comment]
> Bu use_frameworks'ü eklediniz mi? :linkage => :pod dosyanızda statik mi?

Thank you, problem solved
