### ISSUE TITLE
CAS ios error - the application opens and then closes itself

### ISSUE THREAD

**Issue by bayramaliunuvar** [cleveradssolutions/CAS-Flutter#8]
Project; It works before integrating CAS into the project. When CAS is integrated, the following error appears and the application opens and closes on the real device. , 
It was tested on iPhone 6 real device ( IOS: 12.5.7) and ios 15 pro simulator (17.4) devices.

 **ERROR**
![image](https://github.com/cleveradssolutions/CAS-Flutter/assets/16406997/e728288e-d055-4b29-bd22-0fc1f0e5532d)

I followed the steps [here ](https://github.com/cleveradssolutions/CAS-iOS/wiki)

XCODE VERSION: 15.2 (15C500b)
FLUTTER VERSION: 3.13.5
PACKAGE VERSION: clever_ads_solutions: ^0.2.4

FLUTTER DOCTOR:
`Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.13.5, on macOS 14.3 23D56 darwin-x64, locale tr-TR)
    ! Flutter version 3.13.5 on channel [user-branch] at /Users/bau/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.86.2)
[✓] Connected device (1 available)
[✓] Network resources`

**PODFİLE**
`source 'https://cdn.cocoapods.org/'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  $casVersion = '~> 3.5.6'
  pod 'CleverAdsSolutions-SDK/Optimal', $casVersion

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end`

**Comment by bayramaliunuvar** [comment]
@Str4tos iOS simulator also gives the same error as shown in the image.

**Comment by Str4tos** [comment]
Please open a new issue with additional information if the problem still persists. 

This issue is closed due to inactivity.
